services:
  tests:
    build: .
    environment: production
    env:
      BASE_URL: ${{ vars.BASE_URL }}
      BROWSER: ${{ vars.BROWSER }}
      HEADLESS: ${{ vars.HEADLESS }}
      STEP_TIMEOUT: ${{ vars.STEP_TIMEOUT }}
    volumes:
      - ./reports:/app/reports
